In [2]:
from quantpy.mongoclient import MongoData
import numpy as np
import pandas as pd
import math

x = pd.Series([math.nan, 2, 5])
y = pd.Series([3, math.nan, 8])
df = pd.DataFrame([x, y])
df = pd.DataFrame(np.random.randn(10, 5),   columns=['a', 'b', 'c', 'd', 'e'])

print('a' in df.columns)
for item in df.values:
    print(item)

True
[-0.46248847 -1.0573859   0.18357255 -0.49258513 -0.15812884]
[ 1.36358616 -0.59102535 -0.75050653 -1.87151147  1.04160982]
[ 1.60642288  0.66133214  0.53245926 -0.65840455  0.82043816]
[-0.12486372 -0.49075719  0.32697196  0.67730586  1.14840499]
[ 1.90272942  0.48947429 -0.5946197  -0.57658004  0.76419651]
[-1.18184652  0.15541179 -0.99415284  3.35000475 -0.31735286]
[-0.13050648 -1.86894931 -1.06159033 -0.2019576  -1.23293237]
[-1.58714817 -0.83716314 -2.32659879 -0.23302193 -0.3251474 ]
[ 1.46364446  0.21716405 -0.66264542 -0.40578552  0.96029505]
[ 0.31713733  1.33316492  1.8801645  -0.57612681  0.69775158]


In [3]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [6]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [8]:
z = np.ones(3)

In [9]:
x.dot(z)

array([  6.,  15.])

In [15]:
from numpy.random import randn
from numpy.linalg import inv, qr
X = randn(5,5)
X

array([[-0.69056525,  0.17636923,  0.4721399 , -0.91888505, -0.3064998 ],
       [ 0.77357657, -0.42801093, -1.02955894,  1.80728139, -1.04308104],
       [-1.40852197,  1.05649887, -0.2912876 ,  0.87876028,  0.34970702],
       [ 1.92359759,  0.93538371, -1.1365103 ,  0.31656392,  0.95733607],
       [-0.21245284, -0.3817487 , -1.77975279,  1.63927899, -0.82835612]])

In [16]:
X.T

array([[-0.69056525,  0.77357657, -1.40852197,  1.92359759, -0.21245284],
       [ 0.17636923, -0.42801093,  1.05649887,  0.93538371, -0.3817487 ],
       [ 0.4721399 , -1.02955894, -0.2912876 , -1.1365103 , -1.77975279],
       [-0.91888505,  1.80728139,  0.87876028,  0.31656392,  1.63927899],
       [-0.3064998 , -1.04308104,  0.34970702,  0.95733607, -0.82835612]])

In [17]:
mat = X.T.dot(X)
mat

array([[ 6.80459911, -0.06059012, -2.52027604,  1.05553957,  0.92970102],
       [-0.06059012,  2.35116408, -0.1674665 , -0.33687386,  1.97355845],
       [-2.52027604, -0.1674665 ,  5.8269318 , -5.82780649,  1.21358411],
       [ 1.05553957, -0.33687386, -5.82780649,  7.6702837 , -2.35104294],
       [ 0.92970102,  1.97355845,  1.21358411, -2.35104294,  2.90692139]])

In [18]:
inv(mat)

array([[ 0.33381045,  0.46110434,  0.34693676,  0.0862125 , -0.49492495],
       [ 0.46110434,  2.00148342,  0.40656369, -0.23983189, -1.87001548],
       [ 0.34693676,  0.40656369,  1.1650935 ,  0.78132558, -0.24146977],
       [ 0.0862125 , -0.23983189,  0.78132558,  0.85506613,  0.5006201 ],
       [-0.49492495, -1.87001548, -0.24146977,  0.5006201 ,  2.27757804]])

In [19]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   2.22044605e-16,  -8.32667268e-17,
         -1.11022302e-16,   0.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00,   0.00000000e+00,
         -1.11022302e-16,  -8.88178420e-16],
       [  3.33066907e-16,  -4.44089210e-16,   1.00000000e+00,
          7.77156117e-16,   0.00000000e+00],
       [  0.00000000e+00,   8.88178420e-16,  -4.44089210e-16,
          1.00000000e+00,   0.00000000e+00],
       [ -2.22044605e-16,   0.00000000e+00,   0.00000000e+00,
         -2.22044605e-16,   1.00000000e+00]])

In [20]:
q,r = qr(mat)

In [23]:
q

array([[-0.92057876,  0.07393239, -0.30878282, -0.15876688, -0.16283423],
       [ 0.0081971 , -0.76190386,  0.17215708, -0.10613581, -0.61524991],
       [ 0.34096242,  0.03411833, -0.59479173, -0.72283593, -0.07944547],
       [-0.14280155,  0.1175207 ,  0.70740076, -0.66200607,  0.16470798],
       [-0.12577714, -0.63171302, -0.14429854, -0.0527678 ,  0.74934122]])

In [22]:
r

array([[-7.39165335, -0.18217151,  4.98508332, -3.76115269, -0.45579065],
       [ 0.        , -3.08786645, -1.31145624,  2.52247056, -3.50615762],
       [ 0.        ,  0.        , -7.01413659,  8.84761998, -2.75173751],
       [ 0.        ,  0.        ,  0.        , -0.87299744,  0.16871969],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.32900792]])