In [23]:
from quantpy.mongoclient import MongoData
import numpy as np
import pandas as pd
import math

x = pd.Series([math.nan, 2, 5])
y = pd.Series([3, math.nan, 8])
df = pd.DataFrame([x, y])
df = pd.DataFrame(np.random.randn(10, 5),   columns=['a', 'b', 'c', 'd', 'e'])

print('a' in df.columns)
for item in df.values:
    print(item)

True
[ 0.44308778  0.34038468  0.6343543   0.60580054 -0.55032128]
[ 0.12359246  0.3541178  -0.8193287  -1.77854005  0.8808503 ]
[ 2.56718134 -0.77409637  1.03937281  0.76907949 -0.01127842]
[ 0.65942365 -0.04298669  0.2236282   0.30578886 -0.08815863]
[ 0.267563   -0.45226403 -0.1536983  -0.22094552 -1.17111439]
[-0.11478032 -0.18049808  1.93976543 -0.58200635 -0.09534485]
[-0.61536553 -0.26144795  1.27031665 -0.24107885 -0.17065838]
[-0.00723507 -0.03512007 -1.11168308  1.62562552 -0.74245651]
[-1.88105207 -0.1243322   0.92494406 -0.07074403  0.78203683]
[ 0.24653727 -1.11810585  0.53554403 -0.68496888 -1.46445757]
